### ISSUE TITLE
Capture Failed with Exception: access violation reading 0x0000000000000000

### ISSUE THREAD

**Issue by coolermzb3** [lovettchris/wincam#16]
Windows 11 Professional Workstation Edition
24H2
OS version: 26100.3476
Windows Features Experience Pack: 1000.26100.54.0

**Comment by lovettchris** [comment]
I'll need more information, like what code are you running exactly?

**Comment by lovettchris** [comment]
I see the bug, thanks, the problem is you cannot ask for a bounds that overlaps 2 monitors, which is what this message is saying:

> Monitor not found that fully contains the bounds (3000, 2) (10 x 10)

So you cannot continue after this message, but it should not crash.  I pushed a fix and new wincam version 1.0.14  that should fix the crash.

You need to provide a region fully inside the primary monitor (0,0) size (2560 x 1440) or fully inside the monitor starting at (2560, 555) size (1920 x 1080), which appears to be oddly positioned 555 pixels below your primary monitor (probably because it has a vertical resolution of only 1080 whereas your primary monitor has 1440.

By specifying a Y location of 2 you are placing your region above your secondary monitor outside of its legal bounds.  So try this instead:

> python .\mirror.py --x 3000 --y 557 --width 10 --height 10

Strangely when I try this on my machine I do not get a crash I get this instead:

> Monitor not foundfailed with HRESULT: 80004005: Unspecified error
> Monitor not foundfailed with HRESULT: 80004005: Unspecified errorfailed with HRESULT: 80004005: Unspecified error
> Error: [WinError -529697949] Windows Error 0xe06d7363

**Comment by coolermzb3** [comment]
I upgraded to ver 1.0.14 and it still doesn't work.

Perhaps my previous explanation was still unclear. It fails with the same error, regardless of whether I provide arguments or not, and regardless of what arguments I provide. This suggests the issue maybe unrelated to window size. Here are details:

1. below are the same in both v1.0.12 and v1.0.14
```
$ python .\mirror.py                                      
Press ESCAPE to close the window...
Error: exception: access violation reading 0x0000000000000000

$ python .\mirror.py --x 1 --y 2 --width 3 --height 4                                     
Press ESCAPE to close the window...                                                                                                                                
Error: exception: access violation reading 0x0000000000000000
```
2. below are slightly different on the last line
```
$ python .\mirror.py --x 3000 --y 2 --width 10 --height 10
Press ESCAPE to close the window...
Monitor not found that fully contains the bounds (3000, 2) (10 x 10)
Found monitor at (2560, 555) size (1920 x 1080)
Found monitor at (0, 0) size (2560 x 1440)
Monitor not foundfailed with HRESULT: 80004005: *gc歔剉曪
Monitor not foundfailed with HRESULT: 80004005: *gc歔剉曪媐ailed with HRESULT: 80004005: *gc歔剉曪
--- Error: exception: access violation reading 0x0000000000000000  # v1.0.12
+++ Error: [WinError -529697949] Windows Error 0xe06d7363 # v1.0.14
```

**Comment by lovettchris** [comment]
Interesting, well sounds like you have a solution then which is to use python 3.10 and clean conda env.  In your old environment did you try this?
> pip uninstall wincam -y
> pip install wincam

**Comment by coolermzb3** [comment]
Yes, but not work. I upgraded numpy, opencv, pywin32 (required by wincam) to the latest version, still not work.
Anyway, it might be incompatible with some certain libraries in my old env, and it's not your bug, so you might want to close the issue.
Thank you!
